
title: Yinghang Chen's Homepage
page-top-title: Yinghang Chen
top-section-bg-text: A Ph.D. student in the Department of Statistics at SUSTech
home-subtitle: Yinghang Chen
copyright-text: '&copy; Yinghang Chen 2023. All Rights Reserved.'
